# Generated by Django 4.0.6 on 2022-08-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebanxSearch', '0002_rename_department_profile_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Department',
            new_name='department_id',
        ),
    ]
