# Generated by Django 4.1 on 2022-08-20 01:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebanxSearch', '0003_rename_department_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='ebanxSearch.department'),
            preserve_default=False,
        ),
    ]
