# Generated by Django 4.1 on 2022-08-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebanxSearch', '0004_remove_profile_department_id_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='ebanxSearch.department'),
        ),
    ]
