# Generated by Django 4.1 on 2022-08-20 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebanxSearch', '0005_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='ebanxSearch.department'),
        ),
    ]
