# Generated by Django 4.1 on 2022-08-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebanxSearch', '0006_remove_profile_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ManyToManyField(blank=True, to='ebanxSearch.department'),
        ),
    ]
